language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install codecov

# we need the delta filter command, so must install in-place
  - pip install -e .

# command to run tests
# Use --nocapture with nosetests to get extra verbose output for debugging on Travis
script:
  - pytest -v --cov=./

# application dependencies: BLAST+, legacy BLAST, MUMMER
before_install:
  - cd $HOME
  - cd $TRAVIS_BUILD_DIR

sudo: false
addons:
  apt:
    packages:
    - csh
    - ncbi-blast+
    - mummer

# Use codecov for code coverage
after_success:
  - codecov